import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ToastProvider from "@/providers/ToastProvider";
import getCurrentUser from "./action/getCurrentUser";
import ClientOnly from "@/components/ClientOnly";
import Modal from "@/components/modals";
import RentModals from "@/components/modals/MainModals";
import Popup from "@/components/navbar/Popup";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <RentModals />
          <ToastProvider />
          <Popup currentUser={currentUser} />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
